const tripImageTypes = {
    GET_TRIP_IMAGES_START: "GET_TRIP_IMAGES_START",
    GET_TRIP_IMAGES_SUCCESS: "GET_TRIP_IMAGES_SUCCESS",
    GET_TRIP_IMAGES_FAILURE: "GET_TRIP_IMAGES_FAILURE",
};

export default tripImageTypes;