const tripImageTypes = {
    GET_TRIP_IMAGES_START: "GET_TRIP_IMAGES",
    GET_TRIP_IMAGES_SUCCESS: "GET_TRIP_IMAGES_SUCCESS",
    GET_TRIP_IMAGES_FAILURE: "GET_TRIP_IMAGES",
};

export default tripImageTypes;