const tripDetailTypes = {
    GET_TRIP_DETAIL_START: "GET_TRIP_DETAIL_START",
    GET_TRIP_DETAIL_SUCCESS: "GET_TRIP_DETAIL_SUCCESS",
    GET_TRIP_DETAIL_FAILURE: "GET_TRIP_DETAIL_FAILURE",

    TRIP_DETAIL_CLEAN: "TRIP_DETAIL_CLEAN",
};

export default tripDetailTypes;